version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - .:/app                           # Volumen para sincronizar el código
      - db_data:/app/trivia.db           # Volumen para persistir la base de datos
    command: flask run --host=0.0.0.0    # Ejecuta la aplicación

volumes:
  db_data:                               # Volumen para persistencia de la base de datos
