"""Add score column to User model

Revision ID: 1b050602d948
Revises: 
Create Date: 2024-11-20 21:19:53.026006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b050602d948'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('trivia_questions')
    op.drop_table('trivia')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('trivia',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trivia_questions',
    sa.Column('trivia_id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['trivia_id'], ['trivia.id'], ),
    sa.PrimaryKeyConstraint('trivia_id', 'question_id')
    )
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_text', sa.VARCHAR(length=255), nullable=False),
    sa.Column('correct_option', sa.VARCHAR(length=100), nullable=False),
    sa.Column('option_1', sa.VARCHAR(length=100), nullable=False),
    sa.Column('option_2', sa.VARCHAR(length=100), nullable=False),
    sa.Column('option_3', sa.VARCHAR(length=100), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
